### PR TITLE
Blog articles Q&A - August 2022

### PR DESCRIPTION
**Pull request by lorenzi-nicolas**
⚠ PLEASE DO NOT DELETE THE TEXT BELOW ⚠

## Pull request's description

This pull request includes the addition of two new blog posts and their images.
Both articles are written transcripts of the Q&A session held in August 2022. They provide clear answers to the questions asked during the session and will allow users to consult them in writing.

## Checklist before merging (please do not edit)
You must review you work before to submit the review to others.

### Self-review of your content
Remember the content must be readable and understandable by someone else than yourself.
- [ ] From a technical point of view.
- [ ] From a grammatical point of view (spelling mistakes, typos, clarity, etc.), and following the guidelines at the bottom.

### External reviews of your content
- [x] You requested a technical review.
- [x] You requested a grammatical review.
- [ ] You validated with @K0rdan or @alexgeron-Luos that it is safe to merge.

### Some guidelines to keep in mind
- Colons (:), semi-colons (;), exclamation (!), and interrogation points (?) are not preceded by a space (like full stops and commas). E.g.: Colons!
- File names and/or address are put in *italic*. E.g.: The file _main.c_.
- Functions, variables, or more generally short codes are put between grave accents. E.g.: To obtain `code()`, type \`code()\`.
- Long codes are put into blocks of code with three grave accent on each side, and the language's name:<br />
\`\`\`c<br />
// Some C language <br />
\`\`\`<br />

- "Luos engine" has a upper case on the **L** for "Luos" and lower case on the **e** for "engine".
- We call it "Luos engine" as a proper name, and ***not*** "the Luos engine".
- Following that fashion, anything that's owned by "Luos engine" implies that we must use `'s` as the standard English rule to show the possessive case, e.g. "Luos engine's API".
- The names pipe, gate, inspector, sniffer, app or application, driver, etc. have a lower case and can be refereed with the determiner `the`. E.g.: The inspector.

### CODE REVIEW

**Review by nicolas-rabault — APPROVED** [review]
Content is ok

**Comment by Simonbdy** [comment]
`What’s the difference of Luos with an embedded OS like ROS?` -> `What is the difference between Luos and an embedded OS like ROS?`
@lorenzi-nicolas could you update the image?
Thanks

**Comment by Simonbdy** [comment]
My last commit is misleading, as it was the second part of reviewing the first file. I still have to review the second file.

For this first part of the article, I spot one ">" character in the code that displays a blockquote on the page. Is it here on purpose? (line 51).
At the end of this first part of the article, I added a strike (`<hr />`) to separate the actual Q&A from the text inviting to go to the second part. You can delete it if it is not the right display, but it should be separated.

Thank you

**Review by Simonbdy — APPROVED** [review]
I pushed a last commit to fix typos.

As for the first part, I separated the Q&A from the conclusion with a `<hr />` separator, please correct if it not the right visual.
The rest is good for me, I approve.

**Pull request merged**
