### PR TITLE
[FEATURE] No-board Get started performing

### PR DESCRIPTION
**Pull request by Salem-Tho**
⚠ PLEASE DO NOT DELETE THE TEXT BELOW ⚠

## Pull request's description
With RC 2.7.0 some new example has been created to work with native HAL allowing to perform the Get started on a computer.
This documentation modification in the get started explain and guide user through the first 2 part when user don't use a board

### Self-review of your content
Remember the content must be readable and understandable by someone else than yourself.
- [x] From a technical point of view.
- [ ] From a grammatical point of view (spelling mistakes, typos, clarity, etc.), and following the guidelines at the bottom.

### External reviews of your content
- [x] You requested a technical review.
- [x] You requested a grammatical review.
- [ ] You validated with @K0rdan or @alexgeron-Luos that it is safe to merge.

### Some guidelines to keep in mind
- Colons (:), semi-colons (;), exclamation (!), and interrogation points (?) are not preceded by a space (like full stops and commas). E.g.: Colons!
- File names and/or address are put in *italic*. E.g.: The file _main.c_.
- Functions, variables, or more generally short codes are put between grave accents. E.g.: To obtain `code()`, type \`code()\`.
- Long codes are put into blocks of code with three grave accent on each side, and the language's name:<br />
\`\`\`c<br />
// Some C language <br />
\`\`\`<br />

- "Luos engine" has a upper case on the **L** for "Luos" and lower case on the **e** for "engine".
- We call it "Luos engine" as a proper name, and ***not*** "the Luos engine".
- Following that fashion, anything that's owned by "Luos engine" implies that we must use `'s` as the standard English rule to show the possessive case, e.g. "Luos engine's API".
- The names pipe, gate, inspector, sniffer, app or application, driver, etc. have a lower case and can be refereed with the determiner `the`. E.g.: The inspector.

### CODE REVIEW

**Review by alexgeron-Luos — APPROVED** [review]

**Review by Simonbdy — CHANGES_REQUESTED** [review]
Please complete this PR's description and checklist

**Review by Simonbdy — APPROVED** [review]
I fixed a few typos, it's ok for me

**Review by Simonbdy — COMMENTED** [review]
At the first page of the Get started (part 1), at the bottom, the "next" button links to the same page, not to the part 2.
Could you please fix the link?

**Comment by Simonbdy** [comment]
> At the first page of the Get started (part 1), at the bottom, the "next" button links to the same page, not to the part 2.
> Could you please fix the link?

Actually now that it's merged, the next button works fine but the first step of the get started doesn't show as a link in the left menu. Only the next steps appear. 

image

The Get started link should automatically select a "Set up you project" link in the left menu

**Pull request merged**
